[workspace]
resolver = "3"
members = [
    "crates/merman",
    "crates/merman-core",
    "crates/merman-cli",
    "crates/merman-render",
    "crates/dugong",
    "crates/dugong-graphlib",
    "crates/manatee",
    "crates/roughr",
    "crates/xtask",
]

[workspace.package]
version = "0.4.0"
edition = "2024"
authors = ["Mingzhen Zhuang <superfrankie621@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Latias94/merman"
homepage = "https://github.com/Latias94/merman"
rust-version = "1.94"

[workspace.dependencies]
base64 = "0.22.1"
euclid = "0.22"
htmlize = { version = "1.1", features = ["unescape"] }
indexmap = { version = "2.14", features = ["serde"] }
lalrpop = "0.23.1"
lalrpop-util = "0.23.1"
logos = "0.16.1"
nalgebra = { git = "https://github.com/dimforge/nalgebra.git", default-features = false, features = ["std"] }
pulldown-cmark = "0.13.3"
regex = "1.12"
roxmltree = "0.21.1"
rustc-hash = "2.1.2"
ryu-js = "1.0.2"
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = { version = "1.0.149", features = ["preserve_order"] }
serde_yaml = { package = "yaml_serde", version = "0.10" }
svgtypes = "0.16"
json5 = "1.3.1"
thiserror = "2.0.18"
tracing = "0.1.44"
futures = "0.3.32"
hashbrown = "0.17.0"
lol_html = "2.7.2"
url = "2.5.8"
uuid = { version = "1.23.1", features = ["v4"] }
chrono = { version = "0.4.44", features = ["clock"] }
resvg = "0.47.0"
usvg = "0.47.0"
tiny-skia = "0.12.0"
unicode-width = "0.2.2"

# Workspace crates (publishable). Keeping versions explicit makes `cargo publish` work without
# duplicating version requirements across crates.
merman = { path = "crates/merman", version = "0.4.0" }
merman-core = { path = "crates/merman-core", version = "0.4.0" }
merman-render = { path = "crates/merman-render", version = "0.4.0" }
merman-cli = { path = "crates/merman-cli", version = "0.4.0" }
dugong = { path = "crates/dugong", version = "0.4.0" }
dugong-graphlib = { path = "crates/dugong-graphlib", version = "0.4.0" }
manatee = { path = "crates/manatee", version = "0.4.0" }
roughr = { package = "roughr-merman", path = "crates/roughr", version = "0.12.0" }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
