[package]
name = "merman-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "CLI to parse/layout/render Mermaid diagrams to SVG/PNG/JPG/PDF (headless)."
documentation = "https://docs.rs/merman-cli"
readme = "README.md"
keywords = ["mermaid", "diagrams", "svg", "cli", "headless"]
categories = ["command-line-utilities", "visualization"]

[dependencies]
merman = { workspace = true, features = ["raster"] }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
assert_cmd = "2.2.0"
tempfile = "3.27.0"
png = "0.18.1"
