[package]
name = "merman"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Rust, headless Mermaid implementation (1:1 parity; pinned to mermaid@11.12.3)."
documentation = "https://docs.rs/merman"
readme = "../../README.md"
keywords = ["mermaid", "diagrams", "svg", "parser", "headless"]
categories = ["parser-implementations", "visualization"]

[package.metadata.docs.rs]
features = ["render"]

[features]
default = []
render = ["dep:merman-render", "dep:thiserror"]
raster = [
    "render",
    "dep:image",
    "dep:resvg",
    "dep:usvg",
    "dep:tiny-skia",
    "dep:gif",
    "dep:krilla",
    "dep:krilla-svg",
]

[dependencies]
merman-core.workspace = true
merman-render = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
image = { workspace = true, optional = true }
resvg = { workspace = true, optional = true }
usvg = { workspace = true, optional = true }
tiny-skia = { workspace = true, optional = true }
gif = { version = "0.14.2", optional = true }
krilla = { git = "https://github.com/LaurenzV/krilla.git", optional = true }
krilla-svg = { git = "https://github.com/LaurenzV/krilla.git", optional = true }

[dev-dependencies]
criterion = "0.8.2"
roxmltree.workspace = true

[[bench]]
name = "pipeline"
harness = false
required-features = ["render"]

[[bench]]
name = "flowchart_stress"
harness = false
required-features = ["render"]

[[bench]]
name = "architecture_stress"
harness = false

[[bench]]
name = "architecture_layout_stress"
harness = false
required-features = ["render"]

[[bench]]
name = "mindmap_layout_stress"
harness = false
required-features = ["render"]
