[package]
edition = "2021"
name = "roughr-merman"
version = "0.12.0"
authors = ["orhanbalci@gmail.com <orhanbalci@gmail.com>"]
description = "Fork of roughr (roughjs port) used by merman for Mermaid parity"
homepage = "https://github.com/Latias94/merman"
documentation = "https://docs.rs/roughr-merman"
readme = "README.md"
keywords = [
    "graphics",
    "bezier",
    "sketch",
    "2D",
]
categories = ["graphics"]
license = "MIT"
repository = "https://github.com/Latias94/merman"

[lib]
name = "roughr"
path = "src/lib.rs"

[dependencies]
cgmath = "0.18"
euclid = "0.22"
rand = "0.10.0"
num-traits = "0.2"
derive_builder = "0.20"
svgtypes = "0.16"
palette = "0.7"

[dev-dependencies]
plotlib = "0.5"